version: '3'
services:

  #PHP Service
  app:
    image: nasservb/laravel-php:v8
    container_name: app
    restart: unless-stopped
    depends_on:
      - redis
      - db
    tty: true
    ports:
      - "9001:9000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app-network

 
  front:
    image: node:14-alpine
    container_name: front
    restart: unless-stopped
    depends_on:
      - app
    tty: true
    ports:
      - "3000:3000"
    environment:
      SERVICE_NAME: node
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app-network



  #Nginx Service
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www
      - ./webserver/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jibimo
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql/  
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    tty: true
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=12345678
    hostname: rabbitmq
    depends_on:
      - app
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"   
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    tty: true
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
 
  phpmyadmin:
    image: phpmyadmin:5.0.4    
    restart: unless-stopped
    tty: true
    container_name: phpmyadmin   
    ports:
      - 8080:80
    networks:
      - app-network      
 
#Docker Networks
networks:
  app-network:
    driver: bridge
    
volumes:
  rabbitmq_data: {} 
  mysql_data: {}
  redis_data: {}
